# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH
  GIT_COMMIT:
    sh: git rev-parse HEAD

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Builds the binary into the project root
    cmds:
      - GOARCH={{.GOARCH}} GOOS={{.GOOS}} go build -o . -ldflags="-X main.version={{.GIT_COMMIT}}" ./...

  install:
    desc: Installs the package into the Go bin directory
    cmds:
      - go install -ldflags="-X main.version={{.GIT_COMMIT}}" ./...

  clean:
    desc: Removes build artifacts
    cmds:
      - go clean -r -testcache

  test:
    desc: Runs the tests
    cmds:
      - go test ./...

  test-all:
    desc: Runs all tests, including coverage and race detection
    cmds:
      - go test ./... -cover -race
      - govulncheck ./...

  snapshot:
    desc: Builds a local multi-platform snapshot using goreleaser (no publish)
    cmds:
      - goreleaser release --snapshot --clean
